double qoutes

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -1,13 +1,14 @@
 #!/usr/bin/env bash
 # Find the Gunicorn master process ID
-MASTER_PID=$(pgrep -f "gunicorn: master")
+PIDS=$(pgrep -f "gunicorn")
 
-# Check if the master PID was found
-if [[ -z "$MASTER_PID" ]]; then
-    echo "Gunicorn master process not found."
-    exit 1
+if [ -z "$PIDS" ]; then
+        echo "Gunicorn process not found. Start Gunicorn first."
+        exit 1
 fi
 
-# Send the HUP signal to the master process to gracefully reload Gunicorn
-kill -HUP "$MASTER_PID"
+for PID in $PIDS; do
+	kill -HUP "$PID"
+done
 
+echo "Reload complete."
